[general]
import = ['./theme.toml']

[window]
padding.x = 0
padding.y = 0

decorations = "Buttonless"

opacity = 1

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font Mono"
normal.style = "Thin"

size = 12
