ohmyzsh/ohmyzsh path:plugins/aws
ohmyzsh/ohmyzsh path:plugins/npm
ohmyzsh/ohmyzsh path:plugins/fnm
ohmyzsh/ohmyzsh path:plugins/tmux

alberti42/tmux-ssh-syncing
ntnyq/omz-plugin-pnpm
lukechilds/zsh-better-npm-completion