set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.tmux/plugins'

set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on

unbind C-b
set -g prefix C-a
bind C-Space send-prefix

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D 
bind k select-pane -U
bind l select-pane -R

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Use Alt-arrow keys without prefix key to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# bind r to tmux conf reload
unbind r
bind r source-file $XDG_CONFIG_HOME/tmux/tmux.conf

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'akohlbecker/aw-watcher-tmux'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @resurrect-capture-pane-contents 'on' # allow tmux-ressurect to capture pane contents
set -g @continuum-restore 'on'


# set vi-mode
set-window-option -g mode-keys vi
# keybindings
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Ensure new panes open with same path
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Setup split for IDE purposes
bind i run-shell "~/.config/tmux/layouts/ide.sh"


# tmux-plugins/tmux-prefix-highlight support
set -g @prefix_highlight_output_prefix "#[fg=#ffc777]#[bg=#1e2030]#[fg=#1e2030]#[bg=#ffc777]"
set -g @prefix_highlight_output_suffix ""

# Themes and stuff

set -g @dracula-plugins "compact-alt cpu-usage ram-usage battery weather"
set -g @dracula-narrow-plugins "compact-alt battery"

set -g @dracula-show-flags true
set -g @dracula-show-empty-plugins false
set -g @dracula-show-powerline true
set -g @dracula-show-edge-icons true
set -g @dracula-show-left-icon "#h"

set -g @dracula-battery-label false
set -g @dracula-show-battery-status true

set -g @dracula-show-fahrenheit false
set -g @dracula-fixed-location "Ghent, Belgium"

set -g @dracula-show-ssh-only-when-connected true

set -g @plugin 'dracula/tmux' 


set-window-option -g window-active-style bg=terminal
set-window-option -g window-style        bg=colour235

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

run -b '~/.tmux/plugins/tpm/tpm'
